package routers

import (
	// "net/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	// _ "github.com/swaggo/gin-swagger/example/basic/docs"
	"github.com/MaximillianoNico/Go-Rest-API/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/MaximillianoNico/Go-Rest-API/internal/controller"
	"github.com/gin-contrib/cors"
)

func SwaggerInit() {
	// programatically set swagger info
	docs.SwaggerInfo.Title = "Swagger Example REST API"
	docs.SwaggerInfo.Description = "This is a sample server."
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "localhost:8080"
	// docs.SwaggerInfo.BasePath = "/v2"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}
}

func InitRouters() *gin.Engine {
	SwaggerInit()
	r := gin.New()
	r.Use(cors.Default())

	// set endpoint for swagger documentation
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json")
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	apiProfiles := r.Group("/api/v1")
	{
		apiProfiles.GET("/ping", controller.BasicRoute)
		apiProfiles.GET("/user/:name/*action", controller.RouteWithParams)

	}

	r.NoRoute(func(c *gin.Context) {
		// In gin this is how you return a JSON response
		c.JSON(404, gin.H{"message": "Not found"})
	})

	return r
}
